### ISSUE TITLE
要连接的数据库不存在时导致框架无法退出成为僵尸进程

### ISSUE THREAD

**Issue by YiwanGi** [zhamao-robot/zhamao-framework#175]
### 受影响版本

2.8.4

### 描述

`php：8.0.17` `swoole：4.8.5`
当数据库不存在时 启动框架后
``` 
[11-30 13:40:57] [I] [#2] Connecting to MySQL pool
[11-30 13:40:57] [I] [#0] Connecting to MySQL pool
[11-30 13:40:57] [I] [#4] Connecting to MySQL pool
[11-30 13:40:57] [E] [#0] Worker加载出错！停止服务！
[11-30 13:40:57] [E] [#0] [ErrCode:E00030] Uncaught ZM\Exception\DbException: [ErrCode:E00043] An exception occurred while executing 'select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA=?;' with params ["bot"]:

SQLSTATE[HY000] [1049] Unknown database 'bot'
#0 /www/wwwroot/project/bot/vendor/zhamao/framework/src/ZM/DB/DB.php(34): ZM\MySQL\MySQLWrapper->fetchAllAssociative()
#1 /www/wwwroot/project/bot/vendor/zhamao/framework/src/ZM/Event/SwooleEvent/OnWorkerStart.php(291): ZM\DB\DB::initTableList()
#2 /www/wwwroot/project/bot/vendor/zhamao/framework/src/ZM/Event/SwooleEvent/OnWorkerStart.php(84): ZM\Event\SwooleEvent\OnWorkerStart->initMySQLPool()
#3 /www/wwwroot/project/bot/vendor/zhamao/framework/src/ZM/Framework.php(686): ZM\Event\SwooleEvent\OnWorkerStart->onCall()
#4 {main}
[11-30 13:40:57] [I] [#1] 正在结束 Worker #1，进程内可能有事务在运行...
[11-30 13:40:57] [I] [#1] 正在结束 Worker #1，进程内可能有事务在运行...
[11-30 13:40:57] [I] [#3] 正在结束 Worker #3，进程内可能有事务在运行...
[11-30 13:40:57] [I] [#3] 正在结束 Worker #3，进程内可能有事务在运行...
[11-30 13:40:57] [I] [#7] 正在结束 Worker #7，进程内可能有事务在运行...
[11-30 13:40:57] [I] [#7] 正在结束 Worker #7，进程内可能有事务在运行...
[11-30 13:40:57] [I] [#7] 正在结束 Worker #7，进程内可能有事务在运行...
[11-30 13:40:57] [I] [#7] 正在结束 Worker #7，进程内可能有事务在运行...
[11-30 13:40:57] [I] [#7] 正在结束 Worker #7，进程内可能有事务在运行...
[11-30 13:40:57] [I] [#7] 正在结束 Worker #7，进程内可能有事务在运行...
[11-30 13:40:57] [I] [#7] 正在结束 Worker #7，进程内可能有事务在运行...
[11-30 13:40:57] [I] [#7] 正在结束 Worker #7，进程内可能有事务在运行...
[11-30 13:40:57] [I] [#7] 正在结束 Worker #7，进程内可能有事务在运行...
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^Z
[1]+  Stopped                 vendor/bin/start server
``` 
通过  `lsof -i:20001` 以及 `kill -9 PID` 杀死相关进程后 主进程依然存在
``` 
检测到已经在 pid: 13486 进程启动了框架！
不可以同时启动两个框架！
```

### 复现步骤

``` 
composer require zhamao/framework  
vendor/bin/start init
# 修改mysql配置 当库不存在时
vendor/bin/start server
```

**Comment by crazywhalecc** [comment]
如果存在僵尸进程，可以通过 `vendor/bin/start server:stop --force` 命令强行杀死。

关于数据库无法连接时导致卡死，需要提供下更多信息，例如是数据库服务器没有启动，还是目标数据库服务器内的指定数据库不存在。

**Comment by YiwanGi** [comment]
> 如果存在僵尸进程，可以通过 `vendor/bin/start server:stop --force` 命令强行杀死。
> 
> 关于数据库无法连接时导致卡死，需要提供下更多信息，例如是数据库服务器没有启动，还是目标数据库服务器内的指定数据库不存在。

是目标数据库服务器内的指定数据库不存在

**Comment by crazywhalecc** [comment]
目前找不到数据库确实会报错，但是我这边本地尝试了很多次也无法复现残留僵尸进程的问题。关于僵尸进程的形成有很多种可能，建议尝试以下方式进行调试：

1. 将 `worker_num` 配置调整为 1，然后测试有无残留进程。
2. 将 runtime 种的 Swoole 运行模式由 SWOOLE_PROCESS 调整为 SWOOLE_BASE 模式，测试有无残留进程。
3. 新建一个 onWorkerStart 事件，设置 `worker_num` 为多个或默认数量，设置一个可成功连接且存在的数据库，在回调里面抛出任意一个异常让 Worker 崩溃退出，测试有无残留进程。

如果以上三种情况测试下来均无问题，初步怀疑可能为系统 Swoole 版本或框架内部机制原因。如果升级 Swoole 到 4.8.x 最新版也可以稳定复现你的问题，建议将 config/global.php 中的配置文件内容、`php --ri swoole`、`./zhamao server --preview` 脱敏后贴出（即删除敏感的服务器地址、账户名和密码等信息）。

**Comment by crazywhalecc** [comment]
请尽快反馈下上面的测试样本，有助于我们调试和定位 Bug 所在。如果现在已自行解决或没有其他问题，此 Issue 将在 7 天内关闭。
